//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public int OBJECTID_12 { get; set; }
        public Nullable<int> OBJECTID_1 { get; set; }
        public Nullable<decimal> OBJECTID { get; set; }
        public Nullable<decimal> ADDRESS_ID { get; set; }
        public Nullable<decimal> REGION_ID { get; set; }
        public Nullable<decimal> RESID_ID { get; set; }
        public string RESID_NAME { get; set; }
        public string NAME_AZ { get; set; }
        public string ADDRESS_NA { get; set; }
        public string ADDRESS_NU { get; set; }
        public string REGION_NAM { get; set; }
        public string ADDRESS__1 { get; set; }
        public string GLOBALID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
