//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUILDING1
    {
        public int OBJECTID { get; set; }
        public Nullable<int> ID { get; set; }
        public string NAME { get; set; }
        public string EXPLONATIO { get; set; }
        public string REGION { get; set; }
        public string ACTION { get; set; }
        public string ASSIGMENT { get; set; }
        public string PROTECTING { get; set; }
        public Nullable<decimal> TOTAL_AREA { get; set; }
        public string TECHNICAL_ { get; set; }
        public string USING_MODE { get; set; }
        public string PROPERTY_T { get; set; }
        public string PROPERTY { get; set; }
        public string SERVICE_AR { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
