//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUILDING
    {
        public int OBJECTID_1 { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public string kategori { get; set; }
        public string kategori_e { get; set; }
        public Nullable<decimal> Shape_Leng { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
