//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASPIAN
    {
        public int OBJECTID { get; set; }
        public Nullable<int> GID { get; set; }
        public string NAME { get; set; }
        public string MP_TYPE { get; set; }
        public string MARINE { get; set; }
        public Nullable<decimal> DEPTH { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
