//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL1
    {
        public int OBJECTID { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public string ASSIGMENT { get; set; }
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        public string EXPLONATION_DATE { get; set; }
        public string SERVED_AREA { get; set; }
        public string ACTIVITY { get; set; }
        public string PROPERTY_TYPE { get; set; }
        public string PROPERTY { get; set; }
        public string TECHNICAL_CONDITION { get; set; }
        public Nullable<decimal> WATERPROOF_WIDTH { get; set; }
        public string SERVERD_REGION { get; set; }
        public string KIND { get; set; }
        public Nullable<decimal> DEVICE_SUM { get; set; }
        public string SOURCE { get; set; }
        public Nullable<decimal> FACTICAL_LENGTH { get; set; }
        public string EMPLOYEE { get; set; }
        public string COVER_TYPE { get; set; }
        public string SIBS { get; set; }
        public string CHANNEL_ID { get; set; }
        public Nullable<short> ID_CHANNEL { get; set; }
        public string RESID_IDS { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
