//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL
    {
        public int OBJECTID { get; set; }
        public string Name { get; set; }
        public string assigment { get; set; }
        public string Channel1 { get; set; }
        public string water_capa { get; set; }
        public string exlo_date { get; set; }
        public string served_reg { get; set; }
        public string served_are { get; set; }
        public string length { get; set; }
        public string type { get; set; }
        public string water_rele { get; set; }
        public string tech_condi { get; set; }
        public string wtrprf_wid { get; set; }
        public string ownership { get; set; }
        public string property_t { get; set; }
        public string action { get; set; }
        public string device_tot { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
