//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL_1
    {
        public int OBJECTID { get; set; }
        public Nullable<int> Id { get; set; }
        public string Adı { get; set; }
        public string Mənbəyi { get; set; }
        public Nullable<decimal> Uzunluq { get; set; }
        public Nullable<decimal> Su_Buraxma { get; set; }
        public Nullable<decimal> Üst_e { get; set; }
        public Nullable<decimal> Dib_e { get; set; }
        public Nullable<decimal> Dərinlik { get; set; }
        public Nullable<decimal> Mailliyi { get; set; }
        public Nullable<decimal> Orta_en_k { get; set; }
        public Nullable<decimal> Ümumi_h { get; set; }
        public Nullable<decimal> Xidməte_s { get; set; }
        public Nullable<decimal> F_İ_Ə { get; set; }
        public Nullable<decimal> Hidrotexni { get; set; }
        public Nullable<decimal> Su_ay { get; set; }
        public Nullable<decimal> Hidropostl { get; set; }
        public string ör_n { get; set; }
        public string Növ { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
