//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COAST_LINE
    {
        public int OBJECTID_1 { get; set; }
        public Nullable<int> F_OBJECTID { get; set; }
        public Nullable<int> GID { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<decimal> SHAPE_LENG { get; set; }
        public Nullable<short> F_STATUS { get; set; }
        public string NAME_AZ { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
