//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE
    {
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public string EMPLOYEE { get; set; }
        public string CHANNEL_ID { get; set; }
        public Nullable<short> ID_CHANNEL { get; set; }
        public string LOCATED_NETWORK { get; set; }
        public string EXPLONATION_DATE { get; set; }
        public string NETWORK_TYPE { get; set; }
        public string WATER_CAPABILITY { get; set; }
        public string Activity { get; set; }
        public string PROPERTY_TYPE { get; set; }
        public string Property { get; set; }
        public string TECHNICAL_CONDITION { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
