//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRENAJ
    {
        public int OBJECTID { get; set; }
        public string KIND { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> WATERPROOF_WIDTH { get; set; }
        public Nullable<decimal> SERVED_AREA { get; set; }
        public string PASSING_AREAS { get; set; }
        public string TECHNICAL_CONDITION { get; set; }
        public Nullable<decimal> DEVICE_SUM { get; set; }
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        public string PROPERTY_TYPE { get; set; }
        public string PROPERTY { get; set; }
        public Nullable<decimal> FACTICAL_LENGTH { get; set; }
        public string EXPLONATION_DATE { get; set; }
        public string ACTIVITY { get; set; }
        public string NAME { get; set; }
        public string ASSIGMENT { get; set; }
        public string WATER_CONSUPTION { get; set; }
        public string DRENAJ_RECIEVER { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
