//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HYDRO_POLY
    {
        public int OBJECTID { get; set; }
        public Nullable<decimal> gid { get; set; }
        public Nullable<decimal> id { get; set; }
        public string name { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
