//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUMPSTATION
    {
        public int OBJECTID { get; set; }
        public string PLACED_AREA { get; set; }
        public string PLACED_SOURCE { get; set; }
        public string EXPLONATION_DATE { get; set; }
        public string PUMP_KIND { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> POWER { get; set; }
        public Nullable<decimal> PRODUCTIVITY { get; set; }
        public string PURPOSEFUL { get; set; }
        public string NAME { get; set; }
        public string BRAND_OFF_AGGREGATE { get; set; }
        public string PIPELINE { get; set; }
        public string AGREGAT_SUM { get; set; }
        public Nullable<decimal> PIPELINE_LENGHT { get; set; }
        public string PIPELINE_DIAMETER { get; set; }
        public string PIPELINE_MATERIAL { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
