//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION_CENTER_1
    {
        public int OBJECTID_1 { get; set; }
        public Nullable<decimal> OBJECTID { get; set; }
        public string TYPE_AZ { get; set; }
        public string NAMEAZ { get; set; }
        public string TYPE_CODE { get; set; }
        public Nullable<decimal> POINTTYPE { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
