//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESIDENTIAL_AREA
    {
        public int OBJECTID { get; set; }
        public Nullable<decimal> gid { get; set; }
        public Nullable<decimal> F__gid { get; set; }
        public string type_az { get; set; }
        public string type_code { get; set; }
        public string name_az { get; set; }
        public string name_eng { get; set; }
        public string type_eng { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
