//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIVERBAND
    {
        public int OBJECTID { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public string EXPLONATION_DATE { get; set; }
        public string GENERAL_TYPE { get; set; }
        public string TECHNICAL_CONDITION { get; set; }
        public string PROPERTY_TYPE { get; set; }
        public string PROPERTY { get; set; }
        public string ASSIGMENT { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
