//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROAD
    {
        public int OBJECTID_1 { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<decimal> id { get; set; }
        public string name_az { get; set; }
        public string type_az { get; set; }
        public string name_eng { get; set; }
        public string region_nam { get; set; }
        public string resid_name { get; set; }
        public string road_type { get; set; }
        public Nullable<decimal> resid_id { get; set; }
        public Nullable<decimal> region_id { get; set; }
        public Nullable<decimal> road_id { get; set; }
        public Nullable<decimal> ID_ROAD { get; set; }
        public Nullable<decimal> Shape_Leng { get; set; }
        public string road_index { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
