//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WELL
    {
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public string Location { get; set; }
        public string Well_type { get; set; }
        public string Assigment { get; set; }
        public string SIB { get; set; }
        public string Explonation_date { get; set; }
        public Nullable<short> Activity { get; set; }
        public string Irrigated_area { get; set; }
        public string Technical_condition { get; set; }
        public string Depth { get; set; }
        public string Property_type { get; set; }
        public string Property { get; set; }
        public string Number { get; set; }
        public string Productivity { get; set; }
        public string Security_type { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
